/**
 * This file is autogenerated by Scaffold-ETH.
 * You should not edit it manually or your changes might be overwritten.
 */
import { GenericContractsDeclaration } from "~~/utils/scaffold-eth/contract";

const deployedContracts = {
  31337: {
    Tinydemo: {
      address: "0x5FbDB2315678afecb367f032d93F642f64180aa3",
      abi: [
        {
          inputs: [],
          stateMutability: "nonpayable",
          type: "constructor",
        },
        {
          inputs: [
            {
              internalType: "string",
              name: "_programId",
              type: "string",
            },
            {
              internalType: "string",
              name: "_storeId",
              type: "string",
            },
          ],
          name: "creatData",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [],
          name: "getList",
          outputs: [
            {
              components: [
                {
                  internalType: "string",
                  name: "programId",
                  type: "string",
                },
                {
                  internalType: "string",
                  name: "storeId",
                  type: "string",
                },
              ],
              internalType: "struct Tinydemo.Data[]",
              name: "",
              type: "tuple[]",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
      ],
      inheritedFunctions: {},
    },
  },
} as const;

export default deployedContracts satisfies GenericContractsDeclaration;
